apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-chant-tls
spec:
  secretName: hello-chant-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hello-chant.inevitable.fyi
