apiVersion: v1
kind: Namespace
metadata:
  name: calcom

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: calcom-tls
spec:
  secretName: calcom-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - cal.jakegaylor.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calcom
  labels:
    app: calcom
  annotations:
    secrets.infisical.com/auto-reload: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calcom
  template:
    metadata:
      labels:
        app: calcom
    spec:
      containers:
        - name: calcom
          image: docker.io/calcom/cal.com:v6.1.5-arm
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NEXT_PUBLIC_WEBAPP_URL
              value: https://cal.jakegaylor.com
            - name: NEXTAUTH_URL
              value: https://cal.jakegaylor.com
            - name: CALCOM_TELEMETRY_DISABLED
              value: '1'
            - name: NEXT_PUBLIC_LICENSE_CONSENT
              value: agree
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: calcom-pg-app
                  key: uri
            - name: DATABASE_DIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: calcom-pg-app
                  key: uri
            - name: EMAIL_FROM
              value: cal@updates.inevitable.fyi
            - name: EMAIL_FROM_NAME
              value: Jake Gaylor
            - name: EMAIL_SERVER_HOST
              value: smtp.resend.com
            - name: EMAIL_SERVER_PORT
              value: '465'
            - name: EMAIL_SERVER_USER
              value: resend
          envFrom:
            - secretRef:
                name: calcom-secrets
          resources:
            requests:
              cpu: '250m'
              memory: '768Mi'
            limits:
              memory: '2Gi'
          startupProbe:
            httpGet:
              path: /auth/login
              port: http
            periodSeconds: 10
            failureThreshold: 45
          readinessProbe:
            httpGet:
              path: /auth/login
              port: http
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 30

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: calcom
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cal.jakegaylor.com`)
      kind: Rule
      services:
        - name: calcom
          port: 3000
  tls:
    secretName: calcom-tls

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: calcom-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`cal.jakegaylor.com`)
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: default
      services:
        - name: calcom
          port: 3000

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: calcom-pg
spec:
  instances: 1
  bootstrap:
    initdb:
      database: calendso
      owner: calcom
  storage:
    storageClass: longhorn
    size: '5Gi'
  resources:
    requests:
      cpu: '50m'
      memory: '256Mi'
    limits:
      memory: '512Mi'

---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: calcom-secrets
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local:8080
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: '187477dd-1cf2-4a4d-932e-80495fea4db0'
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: calcom-infisical
        namespace: calcom
      secretsScope:
        projectSlug: calcom-8kfu
        envSlug: prod
        secretsPath: /
  managedSecretReference:
    secretName: calcom-secrets
    secretNamespace: calcom
    creationPolicy: Orphan

---
apiVersion: v1
kind: Service
metadata:
  name: calcom
  labels:
    app: calcom
spec:
  type: ClusterIP
  selector:
    app: calcom
  ports:
    - name: http
      port: 3000
      targetPort: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calcom-infisical
