// Django's SECRET_KEY and the field-level ENCRYPTION_SALT_KEYS, sourced from
// home-cloud's on-prem Infisical (see home-cloud's CLAUDE.md "Secrets
// Management" section) rather than generated by us — chant synthesis is
// pure/deterministic and has no business minting secrets.
//
// MANUAL STEP REQUIRED before this app can deploy: run the
// `/add-secret-via-infisical` skill in home-cloud to create the `posthog`
// project, a `posthog-operator` machine identity (Kubernetes-native auth,
// scoped to the `posthog-infisical` ServiceAccount below), and the two
// secret values themselves:
//   - SECRET_KEY: 56 hex-ish chars — `head -c 28 /dev/urandom | sha224sum -b | head -c 56`
//   - ENCRYPTION_SALT_KEYS: 32 hex chars — `openssl rand -hex 16`
//     (do not rotate on a live instance — it invalidates already-encrypted data)
// Then fill in `identityId` and `projectSlug` below with the values the skill
// prints (see k8s/mem0/infisicalsecret.yaml in home-cloud for the reference
// shape this mirrors).
import { InfisicalSecret } from "./crds.js";
import { ServiceAccount } from "@intentius/chant-lexicon-k8s";

export const infisicalServiceAccount = new ServiceAccount({
  metadata: { name: "posthog-infisical", labels: { "app.kubernetes.io/name": "posthog-infisical" } },
});

export const infisicalSecret = new InfisicalSecret({
  metadata: { name: "posthog-secrets", labels: { "app.kubernetes.io/name": "posthog-secrets" } },
  spec: {
    hostAPI: "http://infisical.infisical.svc.cluster.local:8080",
    resyncInterval: 60,
    authentication: {
      kubernetesAuth: {
        // TODO: replace with the posthog-operator machine identity's ID
        // after running /add-secret-via-infisical in home-cloud.
        identityId: "REPLACE_ME_POSTHOG_OPERATOR_IDENTITY_ID",
        autoCreateServiceAccountToken: true,
        serviceAccountRef: { name: "posthog-infisical", namespace: "posthog" },
        secretsScope: {
          // TODO: replace with the auto-generated project slug from the
          // /add-secret-via-infisical run.
          projectSlug: "REPLACE_ME_POSTHOG_PROJECT_SLUG",
          envSlug: "prod",
          secretsPath: "/",
        },
      },
    },
    managedSecretReference: {
      // Materializes a Secret named `posthog-secrets` holding SECRET_KEY and
      // ENCRYPTION_SALT_KEYS. Consumed via secretKeyRef in web.ts/worker.ts.
      secretName: "posthog-secrets",
      // Not a metadata.namespace (WK8001 doesn't apply) — this is a CRD spec
      // field telling the operator where to materialize the Secret, and
      // Flux's targetNamespace doesn't reach into CRD spec bodies.
      secretNamespace: "posthog",
      creationPolicy: "Orphan",
    },
  },
});
