apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-world-tls
spec:
  secretName: hello-world-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hello-world.inevitable.fyi
